heat_template_version: 2013-05-23
description: Simple template to deploy a single compute instance

parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for compute instance
    default: centos7-software-config-26-11-15
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used
    default: m1.small
  key:
    type: string
    label: Key name
    description: Name of key-pair to be used for compute instance
    default: pasc_key
  private_network:
    type: string
    label: Private network name or ID
    description: Network to attach instance to.
    default: network-deploy
  public_network:
    type: string
    label: Public Network name or ID
    description: Public Network with floating IP addresses
    default: ext-net

resources:
  private_net:
    type: OS::Neutron::Net
    properties:
      name: { get_param: private_network }

  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: private_net }
      cidr: 192.168.1.0/24

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: { get_param: public_network }

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router}
      subnet: { get_resource: private_subnet}

  instance_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: private_net }

  my_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key }
      networks:
        - port: { get_resource: instance_port }

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_network }

  floating_ip_assoc:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: floating_ip }
      port_id: { get_resource: instance_port }

outputs:
  instance_ip:
    description: IP address of the instance
    value: { get_attr: [my_instance, first_address] }
  instance_floating_ip:
    description: Floating IP address of the instance
    value: { get_attr: [floating_ip, floating_ip_address] }
